Retro games list is now online! :web:
KAUTH/Retro-Gamez pull request #23
Opened 2020-10-17 01:49 UTC by paulopacitti

## Description :pencil2:
- Changed `game_list.js` to `game_list.json`;
- Replaced `var` with `const` and `let` (best practices);
- Added `<meta charset...` for web compatibility;
- Now the games list is fetched via `GET` from GitHub, so it's not necessary anymore to release a new version of the browser extension everytime a new game is added to the list;
- The GitHub endpoint is pointed to my forked repo, so before merging this PR, make sure to mention me so I can change it or you can change by this endpoint yourself too :)

2020-10-28 20:23 UTC, paulopacitti commented
@KAUTH waiting for your approval ;)

2020-10-31 15:17 UTC, KAUTH commented
> @KAUTH waiting for your approval ;)

Hey thanks for the PR, I will review it ASAP! 😊

2020-10-31 16:40 UTC, KAUTH requested changes

2020-10-31 16:40 UTC, KAUTH commented on retro-gamez/popup/retro_gamez.html
> +    <title>RETRO GAMEZ</title>
Change title to "Retro-Gamez"

2020-10-31 16:40 UTC, KAUTH commented on retro-gamez/popup/game_list.json
> +[
Copy the latest list of games from the repo.

2020-10-31 16:40 UTC, KAUTH commented on retro-gamez/popup/retro_gamez.js
> +async function main() {
I don't believe it is necessary to have a main() function:

[Stack Overflow 1](https://stackoverflow.com/questions/9015836/why-doesnt-javascript-need-a-main-function#:~:text=Many%20programming%20languages%20require%20a,a%20function%20is%20not%20required.)
[Stack Overflow 2](https://stackoverflow.com/questions/8629859/main-function-in-javascript/8629865)

2020-10-31 16:46 UTC, KAUTH commented on retro-gamez/popup/retro_gamez.js
> +async function main() {
I just realized you have a main() function or a function for that matter in order to use async and wait.

[Stack Overflow](https://stackoverflow.com/questions/43832490/is-it-possible-to-use-await-without-async-in-js#:~:text=No.,sense%20in%20an%20async%20function.)

2020-10-31 17:21 UTC, paulopacitti commented on retro-gamez/popup/retro_gamez.js
> +async function main() {
> I just realized you have a main() function or a function for that matter in order to use async and wait.
exactly hahahaha

2020-10-31 17:28 UTC, paulopacitti commented
Resolved your requests! @KAUTH

2020-10-31 19:04 UTC, KAUTH approved these changes

2020-10-31 19:32 UTC, merged